/** Generated by scripts/sync-plugin-version.py — do not edit manually. */
export const FRENCH_READER_PLUGIN_INFO = {
  "name": "french-reading-assistant",
  "displayName": "French Reading Assistant",
  "version": "0.5.0",
  "apiVersion": 1,
  "minStirlingVersion": "2.0.0",
  "channel": "portable",
  "build": {
    "platform": "dev",
    "id": "0.5.0-20260615-134740",
    "builtAt": "2026-06-15T13:47:40+00:00"
  }
} as const;

export const FRENCH_READER_PLUGIN_VERSION = "0.5.0" as const;
export const FRENCH_READER_PLUGIN_NAME = "french-reading-assistant" as const;
export const FRENCH_READER_BUILD_ID = "0.5.0-20260615-134740" as const;
export const FRENCH_READER_BUILD_PLATFORM = "dev" as const;
