/** Generated by scripts/sync-plugin-version.py — do not edit manually. */
export const FRENCH_READER_PLUGIN_INFO = {
  "name": "french-reading-assistant",
  "displayName": "French Reading Assistant",
  "version": "0.5.1",
  "apiVersion": 1,
  "minStirlingVersion": "2.0.0",
  "channel": "portable",
  "build": {
    "id": "0.5.1-20260616-153546",
    "builtAt": "2026-06-16T15:35:46+00:00"
  }
} as const;

export const FRENCH_READER_PLUGIN_VERSION = "0.5.1" as const;
export const FRENCH_READER_PLUGIN_NAME = "french-reading-assistant" as const;
export const FRENCH_READER_BUILD_ID = "0.5.1-20260616-153546" as const;
export const FRENCH_READER_BUILD_PLATFORM = "" as const;
