#!/usr/bin/env python3
"""Sync extensions/french-reader-version.json into engine + frontend artifacts."""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION_FILE = ROOT / "extensions" / "french-reader-version.json"
ENGINE_JSON = (
    ROOT / "extensions" / "french-reader-engine" / "src" / "french_reader" / "_plugin_version.json"
)
FRONTEND_TS = (
    ROOT / "extensions" / "french-reader-frontend" / "src" / "services" / "frenchReaderVersion.ts"
)
PYPROJECT = ROOT / "extensions" / "french-reader-engine" / "pyproject.toml"


def load_base() -> dict:
    data = json.loads(VERSION_FILE.read_text(encoding="utf-8"))
    required = ("name", "displayName", "version")
    missing = [key for key in required if key not in data]
    if missing:
        raise SystemExit(f"Missing keys in {VERSION_FILE}: {', '.join(missing)}")
    return data


def write_engine_json(payload: dict) -> None:
    ENGINE_JSON.parent.mkdir(parents=True, exist_ok=True)
    ENGINE_JSON.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_frontend_ts(payload: dict) -> None:
    FRONTEND_TS.parent.mkdir(parents=True, exist_ok=True)
    build = payload.get("build") or {}
    content = f"""/** Generated by scripts/sync-plugin-version.py — do not edit manually. */
export const FRENCH_READER_PLUGIN_INFO = {json.dumps(payload, indent=2, ensure_ascii=False)} as const;

export const FRENCH_READER_PLUGIN_VERSION = {json.dumps(payload["version"])} as const;
export const FRENCH_READER_PLUGIN_NAME = {json.dumps(payload["name"])} as const;
export const FRENCH_READER_BUILD_ID = {json.dumps(build.get("id", ""))} as const;
export const FRENCH_READER_BUILD_PLATFORM = {json.dumps(build.get("platform", ""))} as const;
"""
    FRONTEND_TS.write_text(content, encoding="utf-8")


def sync_pyproject_version(version: str) -> None:
    if not PYPROJECT.exists():
        return
    text = PYPROJECT.read_text(encoding="utf-8")
    lines = text.splitlines()
    out: list[str] = []
    replaced = False
    for line in lines:
        if line.startswith("version = "):
            out.append(f'version = "{version}"')
            replaced = True
        else:
            out.append(line)
    if replaced:
        PYPROJECT.write_text("\n".join(out) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--platform", default="", help="e.g. windows-x64")
    parser.add_argument("--build-id", default="", help="optional build identifier")
    args = parser.parse_args()

    payload = load_base()
    build: dict[str, str] = {}
    if args.platform:
        build["platform"] = args.platform
    if args.build_id:
        build["id"] = args.build_id
    else:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        build["id"] = f"{payload['version']}-{stamp}"
    build["builtAt"] = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    payload["build"] = build

    write_engine_json(payload)
    write_frontend_ts(payload)
    sync_pyproject_version(payload["version"])
    print(f"[sync-plugin-version] {payload['version']} ({build['id']})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
